# inspired from https://blog.giantswarm.io/getting-started-with-docker-and-meanjs/
# would be nice: http://anandmanisankar.com/posts/docker-container-nginx-node-redis-example/

web:
  build: .
  links:
   - db
  ports:
   - "3000:3000"
   - "35729:35729"
  volumes:
   - ./app:/home/mean/app
  environment:
   NODE_ENV: development
   PORT: 3000
   DB_CONNECTION_NAME: 'db'
   DB_COLLECTION_NAME: 'blog'
db:
  image: mongo:latest
  ports:
   - "27017:27017"
